#include "7_Segment.h"
#include "DIO.h"
#define F_CPU 16000000
#include <util/delay.h>



uint8 numbers[]={0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x10,0x11};

void _7segmentInit(){
	
	DIO_setPinDir(SEGMENT_DATA_PORT,SEGMENT_DATA_PIN1,DIO_PIN_OUTPUT);
	DIO_setPinDir(SEGMENT_DATA_PORT,SEGMENT_DATA_PIN2,DIO_PIN_OUTPUT);
	DIO_setPinDir(SEGMENT_DATA_PORT,SEGMENT_DATA_PIN3,DIO_PIN_OUTPUT);
	DIO_setPinDir(SEGMENT_DATA_PORT,SEGMENT_DATA_PIN4,DIO_PIN_OUTPUT);
	
	DIO_setPinDir(SEGMENT_COM1_PORT,SEGMENT_COM1_PIN,DIO_PIN_OUTPUT);
	DIO_setPinDir(SEGMENT_COM2_PORT,SEGMENT_COM2_PIN,DIO_PIN_OUTPUT);
	DIO_setPinDir(SEGMENT_COM3_PORT,SEGMENT_COM3_PIN,DIO_PIN_OUTPUT);
	DIO_setPinDir(SEGMENT_COM4_PORT,SEGMENT_COM4_PIN,DIO_PIN_OUTPUT);
	
	DIO_setPinValue(SEGMENT_COM1_PORT,SEGMENT_COM1_PIN,DIO_PIN_HIGH);
	DIO_setPinValue(SEGMENT_COM2_PORT,SEGMENT_COM2_PIN,DIO_PIN_HIGH);
	DIO_setPinValue(SEGMENT_COM3_PORT,SEGMENT_COM3_PIN,DIO_PIN_HIGH);
	DIO_setPinValue(SEGMENT_COM4_PORT,SEGMENT_COM4_PIN,DIO_PIN_HIGH);
	
};

void setDigit(uint8 num){
	switch(num)
	{
		case 0:
		DIO_setPinValue(DIO_PORTB,DIO_PIN0,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN1,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN2,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN4,DIO_PIN_LOW);
		break;
		case 1:
		DIO_setPinValue(DIO_PORTB,DIO_PIN0,DIO_PIN_HIGH);
		DIO_setPinValue(DIO_PORTB,DIO_PIN1,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN2,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN4,DIO_PIN_LOW);
		break;
		case 2:
		DIO_setPinValue(DIO_PORTB,DIO_PIN0,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN1,DIO_PIN_HIGH);
		DIO_setPinValue(DIO_PORTB,DIO_PIN2,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN4,DIO_PIN_LOW);
		break;
		case 3:
		DIO_setPinValue(DIO_PORTB,DIO_PIN0,DIO_PIN_HIGH);
		DIO_setPinValue(DIO_PORTB,DIO_PIN1,DIO_PIN_HIGH);
		DIO_setPinValue(DIO_PORTB,DIO_PIN2,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN4,DIO_PIN_LOW);
		break;
		case 4:
		DIO_setPinValue(DIO_PORTB,DIO_PIN0,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN1,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN2,DIO_PIN_HIGH);
		DIO_setPinValue(DIO_PORTB,DIO_PIN4,DIO_PIN_LOW);
		break;
		case 5:
		DIO_setPinValue(DIO_PORTB,DIO_PIN0,DIO_PIN_HIGH);
		DIO_setPinValue(DIO_PORTB,DIO_PIN1,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN2,DIO_PIN_HIGH);
		DIO_setPinValue(DIO_PORTB,DIO_PIN4,DIO_PIN_LOW);
		break;
		case 6:
		DIO_setPinValue(DIO_PORTB,DIO_PIN0,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN1,DIO_PIN_HIGH);
		DIO_setPinValue(DIO_PORTB,DIO_PIN2,DIO_PIN_HIGH);
		DIO_setPinValue(DIO_PORTB,DIO_PIN4,DIO_PIN_LOW);
		break;
		case 7:
		DIO_setPinValue(DIO_PORTB,DIO_PIN0,DIO_PIN_HIGH);
		DIO_setPinValue(DIO_PORTB,DIO_PIN1,DIO_PIN_HIGH);
		DIO_setPinValue(DIO_PORTB,DIO_PIN2,DIO_PIN_HIGH);
		DIO_setPinValue(DIO_PORTB,DIO_PIN4,DIO_PIN_LOW);
		break;
		case 8:
		DIO_setPinValue(DIO_PORTB,DIO_PIN0,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN1,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN2,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN4,DIO_PIN_HIGH);
		break;
		case 9:
		DIO_setPinValue(DIO_PORTB,DIO_PIN0,DIO_PIN_HIGH);
		DIO_setPinValue(DIO_PORTB,DIO_PIN1,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN2,DIO_PIN_LOW);
		DIO_setPinValue(DIO_PORTB,DIO_PIN4,DIO_PIN_HIGH);
		break;
		default:
		break;
		
	}

		_delay_ms(1);
	};

void selectDigit(uint8 digit){
	switch(digit){

		case SEGMENT_COM1:
		CLR_BIT(PORTA,SEGMENT_COM1_PIN);
		SET_BIT(PORTA,SEGMENT_COM2_PIN);
		SET_BIT(PORTB,SEGMENT_COM3_PIN);
		SET_BIT(PORTB,SEGMENT_COM4_PIN);
		break;
		case SEGMENT_COM2:
			SET_BIT(PORTA,SEGMENT_COM1_PIN);
			CLR_BIT(PORTA,SEGMENT_COM2_PIN);
			SET_BIT(PORTB,SEGMENT_COM3_PIN);
			SET_BIT(PORTB,SEGMENT_COM4_PIN);
		break;		
		case SEGMENT_COM3:
			SET_BIT(PORTA,SEGMENT_COM1_PIN);
			SET_BIT(PORTA,SEGMENT_COM2_PIN);
			CLR_BIT(PORTB,SEGMENT_COM3_PIN);
			SET_BIT(PORTB,SEGMENT_COM4_PIN);
		break;
		case SEGMENT_COM4:
			SET_BIT(PORTA,SEGMENT_COM1_PIN);
			SET_BIT(PORTA,SEGMENT_COM2_PIN);
			SET_BIT(PORTB,SEGMENT_COM3_PIN);
			CLR_BIT(PORTB,SEGMENT_COM4_PIN);
		break;
	}
	
	};